# Generated by Django 5.1.6 on 2025-03-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("check_for_files", "0002_fileinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="created_workspaces",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
    ]
